### ISSUE TITLE
Numbers group does not work anymore.

### ISSUE THREAD

**Issue by DutchPete** [noam-sc/obsidian-enhanced-symbols-prettifier#10]
## Bug description
Example: typing a number between 2 parentheses does not convert it to a blue block with the number .

## To reproduce
**Steps to reproduce the behavior:**
1.  type `(1)`, then a space
2. 

**Is the console showing an error ? If yes, what error ?**
(Ctrl + Shift + I to open the console)

![image](https://github.com/user-attachments/assets/c6c1ca5d-7a07-44d8-8772-7e08f21a48b7)

## My setup
 - OS: Linux LMDE 6 FAye
 - Obsidian Version: 1.7.2
 - Plugin Version: 1.4.0

**Additional context**
Add any other context about the problem here if relevant (other plugins ?)

**Comment by noam-sc** [comment]
Hey,
Thanks for reporting this bug.
Disabling the option "Flexible start word boundaries" should make these shortcuts working again.
'(' is detected as a word boundary and not as part of the shortcut text. I'm working on a fix.

**Comment by DutchPete** [comment]
Nope, that does not do the trick. What's more, when I close and relaunch Obsidian, that setting, which I had disabled, is re-enabled.

**Comment by noam-sc** [comment]
The latest latest should fix both issues (1.4.1).
Tell me if it works on your side

**Comment by DutchPete** [comment]
The new version is not yet available in the community collection.
Another oddity: I am using version 0.0.4 – that is a huge gap.

**Comment by noam-sc** [comment]
I don't encounter any issues with a blank Obsidian vault configuration.
![Obsidian_N60jtTLyhL](https://github.com/user-attachments/assets/6746083f-fb2a-4096-b9d7-6cda46e1c16b)

The latest version is available (though the last update date is incorrect, it installs the latest version), and there's no such version as 0.0.4.

Could you try creating a new, blank Obsidian vault? Your current configuration may be corrupted.

**Comment by DutchPete** [comment]
I checked it in the sandbox vault and it works there. When I closed the sandbox vault, main main vault was closed too. When I relaunched it, I noticed the plug-in was at 1.4.0 – I had installed 0.04 through BRAT, I think. After updating to 1.4.1 it now works for me too, even with "Flexible end word boundaries" enabled 😀

Many thanks for your help and my apologies for the confusion.
