### ISSUE TITLE
[FR] option to trigger prettifier by just pressing enter

### ISSUE THREAD

**Issue by albertoloscerritos** [noam-sc/obsidian-enhanced-symbols-prettifier#12]
Hi, thanks for the awesome plugin.

I think it would be cool to have the option for a symbol to be triggered after typing it by just pressing enter.
e.g. at the moment if I type -> in a new line and press enter, the symbol → won't be triggered unless I first press space and the enter.

Thanks for reading.

**Comment by noam-sc** [comment]
Hello,
Thanks for your feedback.

This is indeed a limitation of the plugin.
I haven't figured out yet a way to trigger replacements with the Enter key.

**Comment by noam-sc** [comment]
It should be fixed in the latest release (1.4.2)
