### ISSUE TITLE
Won't Work in Tables

### ISSUE THREAD

**Issue by waddles5g** [noam-sc/obsidian-enhanced-symbols-prettifier#2]
When editing a table in live preview mode the plugin doesn't work (keys don't get replaced by the respective symbols).
In source view it works fine.
(I'm using v1.6.7 on windows)

P.S. Great plugin otherwise, thanks!

**Comment by noam-sc** [comment]
Hey, 
Thanks for noticing this bug!
It should be fixed in the latest release (1.1.2). Tell me if it works on your side.

**Comment by waddles5g** [comment]
Yes, it's working now! Thanks for the (extremly fast) fix 👍
