### ISSUE TITLE
Not just a prettifier!

### ISSUE THREAD

**Issue by danraymond** [noam-sc/obsidian-enhanced-symbols-prettifier#3]
I am using your plugin. I tried  treating it also as generalised replacement tool. Its seems to work very well! Perhaps in the settings you could add a "general" section to use for such cases. I have added my initials to be replaced bu my full name and "myem" to replace by my actual email. Very useful piece of coding well done!

**Comment by noam-sc** [comment]
Thanks for your feedback!
Good idea, I'm also planning to add more general use cases and the ability to share your own shortcuts to other users!

**Comment by noam-sc** [comment]
Hey @danraymond 
The [latest update](https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier/discussions/4) should please you!
